### ISSUE TITLE
gnome-initial-setup monitor icon is very pixelated and unclear

### ISSUE THREAD

**Issue by brs17** [pop-os/icon-theme#1]
**Related Application and/or Shell theming (or name of widget)**
gnome-initial-setup

**Actual issue**
The image on the right is supposed to be a monitor but is very blurry and not clearly a monitor. 
![Screenshot from 2019-04-10 17-16-15](https://user-images.githubusercontent.com/7460774/55921856-d7db5b80-5bbb-11e9-8b1b-87c84a087ce5.png)

This is the case with or without https://github.com/pop-os/icon-theme/pull/61

**Comment by brs17** [comment]
Which pr @isantop ?

**Comment by isantop** [comment]
@brs17 This has been fixed at this point.
