### ISSUE TITLE
SVG Icons have redundant data

### ISSUE THREAD

**Issue by 13r0ck** [pop-os/icon-theme#106]
### Issue Type

Bug Report

### Operating System

Pop_OS

### OS Version

22.04

### Icon Theme Version

```shell
PR #103
```

### What happened?

Each Icon has data of every other icon within it, but just overhang the SVG's viewport. Removing the extra data will be more efficient on users memory, and load faster, as well as make the download smaller.

### Expected Outcome

Icons to not include excess data.

**Comment by isantop** [comment]
Should add that this only affects the fullcolor icons. It is not affecting the scalable/symbolic icons
