### ISSUE TITLE
Some icons are squares

### ISSUE THREAD

**Issue by AAnzel** [pop-os/icon-theme#109]
### Issue Type

Bug Report

### Operating System

Pop_OS

### OS Version

PRETTY_NAME="Pop!_OS 21.10"

### Icon Theme Version

```shell
Installed: 3.0.0~1650300304~21.10~28b598d
```

### What happened?

After the most recent update of the Pop Icon Theme, some icons show as squares. I noticed this in the Gnome Weather top bar widget, as well as in OpenWeather Extension. Images are attached below.

![image](https://user-images.githubusercontent.com/44969003/163993013-3768e05c-2b8b-4c79-81f2-67859a3b2e98.png)

![image](https://user-images.githubusercontent.com/44969003/163993070-bfca1991-e455-4361-add0-392d848c475d.png)

### Expected Outcome

Icons should behave as in the previous version.

**Comment by senntore** [comment]
Yeah this started happening for me as well

**Comment by ahoneybun** [comment]
This happens for me as well. It seems that it happens on 22.04 and 21.10.

**Comment by manuelojeda** [comment]
Confirming issue:
https://user-images.githubusercontent.com/22081875/165117350-114b2707-2c4b-4c20-b7aa-c8a3197b369a.mp4

**Comment by coxackie** [comment]
confirming the issue - especially for the weather icons.

**Comment by red-steve** [comment]
Same
