### ISSUE TITLE
Add KRDC icon in Pop icons.

### ISSUE THREAD

**Issue by doommood** [pop-os/icon-theme#129]
DISTRIB_ID=Pop
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Pop!_OS 22.04 LTS"

Linux pop-os 6.0.6-76060006-generic #202210290932~1669062050~22.04~d94609a SMP PREEMPT_DYNAMIC Mon N x86_64 x86_64 x86_64 GNU/Linux

Pop!OS icon theme does not have or apply the KRDC icon.

![image](https://user-images.githubusercontent.com/29438233/207877072-3468d88d-6516-4767-9f21-5d1d689cc46b.png)

**Comment by isantop** [comment]
Pop does not supply icons for applications, outside of generic applications for general use. KRDC should thus provide their own icon or provide a default name for the application.

**Comment by doommood** [comment]
OK. How can I fix that on my own without using a 3rd party theme? 

Is there any specific configuration folder or file which I can modify to work with a custom icon? I have tried to add custom krdc.svg as krdc.svg and remote-desktop.svg at /usr/share/icons but it didn't work.

It is sad that KRDC flatpack provides the icon (and does not work as should) while KDRC deb does not.

**Comment by isantop** [comment]
I did double-check and it looks like the Debian packaging for KRDC does not include the icon file for the application.

You will need to open a bug with their upstream tracker to have the icon included with the packaging.
