### ISSUE TITLE
Multiple icons have jarring dark edges very apparant in the Light theme

### ISSUE THREAD

**Issue by lboekhorst** [pop-os/icon-theme#130]
### Issue Type

Bug Report

### Operating System

Pop!_OS

### OS Version

Pop!_OS 22.04 LTS

### Icon Theme Version

```shell
3.4.0~1664906042~22.04~ab3e9b1
```

### What happened?

There are several icons which have a jarring dark edge in the light theme that aren't visible in the dark theme:

![image](https://github.com/pop-os/icon-theme/assets/13695841/a26ca96c-5843-4f5f-8715-57911b8134d2)
![image](https://github.com/pop-os/icon-theme/assets/13695841/5c76d7fe-31ca-4eda-92f4-2a3df7b3d99a)
![image](https://github.com/pop-os/icon-theme/assets/13695841/9006fe98-8f87-43b7-86cd-663d7ba7b109)
![image](https://github.com/pop-os/icon-theme/assets/13695841/1ec9ac71-6452-4262-9955-90ba35317644)

It's especially noticeable on the top and the top two corners.

### Expected Outcome

I would expect to see these icons better blend in with the Light theme, as they do with the dark theme:

![image](https://github.com/pop-os/icon-theme/assets/13695841/f0122402-127a-41ff-8599-35ec9ac879e6)
![image](https://github.com/pop-os/icon-theme/assets/13695841/ec137b7d-d81d-4160-a39d-26994236d287)
![image](https://github.com/pop-os/icon-theme/assets/13695841/356a9cae-9fae-4ec4-8789-75bd82fa8b0f)
![image](https://github.com/pop-os/icon-theme/assets/13695841/8b8b1bf3-885e-41ae-bae7-fc854538d20a)

**Comment by leviport** [comment]
I believe that's just part of the icon. I still see the same dark gray edges in dark mode, even in the screenshots you posted.

**Comment by lboekhorst** [comment]
Could be, the dark edges aren't really visible for me on the dark theme, but I don't have a particularly high-end monitor either.

**Comment by isantop** [comment]
This is an intentional design design which helps ensure that the icons remain with a suitable level of contrast when viewed against any color background. Without the border, many of the icons (especially the Text Editor and Settings icons) would be very difficult to see on the light theme. All of our icons are designed with both aesthetics and accessibility in mind.
