### ISSUE TITLE
release please

### ISSUE THREAD

**Issue by soloturn** [pop-os/icon-theme#135]
### Issue Type

Bug Report

### Operating System

n/a

### OS Version

n/a

### Icon Theme Version

```shell
newest from git. can you please create a release, to make packaing and distribution easier.
```

### What happened?

depending on git is cool, but a little painful ... 

### Expected Outcome

version and release.

**Comment by jacobgkau** [comment]
I've tagged and released the current commit as v3.5.0 (that was the latest version number in the changelog, and only docs have been changed since then): https://github.com/pop-os/icon-theme/releases/tag/v3.5.0
