### ISSUE TITLE
Switch Disks icons

### ISSUE THREAD

**Issue by jbicha** [pop-os/icon-theme#14]
**Pop version (if you knew)**

Pop_OS 17.10 Beta (build 27)

**Actual issue**

The app icons for the Disks (gnome-disks) & Disk Usage Analyzer (baobab) apps are identical except that Disks has a Blue i and Disk Usage Analyzer has a red gear. Since Disk Usage Analyzer doesn't actually allow changing any settings as far as I know but it does allow more info about disk usage, I think it would make more sense to switch the icons.

**Comment by WatchMkr** [comment]
Nice catch. Switching them makes sense.

**Comment by SmartFinn** [comment]
Fixed in upstream https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/commit/5fa399a4180daa812e9aa9b53939697e84f633b3

**Comment by isantop** [comment]
This was fixed long ago.
