### ISSUE TITLE
Limited usefulness of emblems for e.g. version control

### ISSUE THREAD

**Issue by chrisjbillington** [pop-os/icon-theme#22]
Here's a screenshot of nautilus in a mercurial repository with the tortoisehg nautilus plugin adding emblems to the icons:

![image](https://user-images.githubusercontent.com/1044087/32417053-5844a14a-c221-11e7-9b01-4f983fdb329c.png)

Can you see which file has changed?

Here's a screenshot with a different icon theme:

![image](https://user-images.githubusercontent.com/1044087/32417071-a6d5c8ac-c221-11e7-9194-e91bf9a0fbf0.png)

With colours on the emblems one can see at a glance which files have changed.

Since this is basically the only use of emblems, it would be nice if they had colour.

And although it's unrelated, I'm curious as to why the pop icon theme shies away from colour for e.g. .py files when other icons and the pop theme more generally are very good at using colour to help contrast different GUI elements so they can be identified quickly.

I know it's probably a design choice to make the emblems monochrome, but since it limits their usefulness I hope you might reconsider.

**Comment by chrisjbillington** [comment]
Ah, fantastic, thank you very much for making the change :)

**Comment by brs17** [comment]
Hello @chrisjbillington! Could you please download the below file, decompress the .deb, install the deb(clicking on it should work just fine), logout/reboot and tell me if this fixes this bug?

[pop-icon-theme_1.1.13~1509991727~17.10~eac208a80ee2009b01cd16edd75977c07b899455_all.zip](https://github.com/pop-os/icon-theme/files/1447462/pop-icon-theme_1.1.13.1509991727.17.10.eac208a80ee2009b01cd16edd75977c07b899455_all.zip)

**Comment by chrisjbillington** [comment]
Thanks, I've tested it it looks pretty good! Here is a screenshot:

![image](https://user-images.githubusercontent.com/1044087/32460238-238bd006-c300-11e7-981d-f4806e8486f5.png)

The red on the "ignored" files is probably too much - it looks like something very dramatic when actually these are the least important files. But actually it seems like the tortoisehg plugin is maybe abusing that emblem, using one of emblem-noread.svg, emblem-unavailable.svg or emblem-unreadable.svg. Maybe I'll submit a pull request to them to just have no emblems on ignored files.

One thing you might want to change though is emblem-rabbitvcs-ignored.svg, which appears to be explicitly for ignored files (even though I am not using rabbitvcs so I don't see it in use), it has been made red - it should probably be grey or one of the bluish greens since ignored means everything is good with the file.

**Comment by isantop** [comment]
Yeah, since the emblem they use generally indicates an error, that's why it was set as red. The specific plugin can choose which emblems to use to indicate which statuses, and in this case emblem-imformation might be a better choice (blue color, plus the icon is literally an i). No emblems would also be a good option, since the lack of an emblem generally indicates it isn't managed.

All of the `vcs-*` icons were already colored, that wasn't something I applied. I assume it was set that way with specific colors in mind, so I didn't think it would be appropriate to change them.

**Comment by chrisjbillington** [comment]
Ah, ok, great. All sounds great to me then!
