### ISSUE TITLE
Stay up-to-date with upstream

### ISSUE THREAD

**Issue by DarthWound** [pop-os/icon-theme#24]
Hello, I know it's time consuming but upstream Papirus team add a lot of new icons very often, it would be great for everybody if Pop could follow that, even if it's only once a week or something like that. Thank you :)

**Comment by isantop** [comment]
We generally try to keep up to date with each new release. There may be exceptions where a new icon is present in upstream, but otherwise we'll try to keep a stable base between releases.

**Comment by DarthWound** [comment]
Thanks. Can't wait for next update then, since upstream added a lot of nice requests :)
