### ISSUE TITLE
Icons in app menu are Adwaita's icon theme

### ISSUE THREAD

**Issue by brs17** [pop-os/icon-theme#27]
**Pop version (if you knew)**
Pop!_OS 19.04: 2.0.0...279cbc8

**Actual issue**
The icon that appears next to the app menu is a black and white Adwaita icon and not an icon from pop-icon-theme.

![screenshot](https://user-images.githubusercontent.com/7460774/55998980-f4d86300-5c7d-11e9-939a-94e50bbbee95.png)
![screenshot2](https://user-images.githubusercontent.com/7460774/55998979-f4d86300-5c7d-11e9-8d99-9af4705404d1.png)

**Comment by isantop** [comment]
Some applications don't have symbolic icons in the current version of the theme. I think the best way around this given the time available would be to use full-color icons in the App menu

**Comment by loxK** [comment]
This and many things I am very disappointed with the massive changes in the icon theme. It looks so mismatched.
