### ISSUE TITLE
Terminal and screenshot icons are very similar

### ISSUE THREAD

**Issue by brs17** [pop-os/icon-theme#28]
**Pop version (if you knew)**
19.04

**Actual issue**
The terminal and screenshot icons look very similar and seeing that they are not very similar/related applications ("Disk usage analyzer" and "Disks"), I do not think it makes sense and is just confusing.

![terminal_screenshot](https://user-images.githubusercontent.com/7460774/56045540-aae39180-5cfe-11e9-8e4e-14d7663a9400.png)

**Comment by brs17** [comment]
Discussed here: https://github.com/pop-os/icon-theme/issues/26

**Comment by isantop** [comment]
For reference, the screenshot icon (and other display-related icons) get a fun, Pop-y blue screen background, as so:

![Screenshot from 2019-04-15 15-24-32](https://user-images.githubusercontent.com/5883565/56166403-c2d34380-5f92-11e9-91f0-1e61b66f0497.png)
