### ISSUE TITLE
Update from 18.10 to 19.04 Changed Icons

### ISSUE THREAD

**Issue by kmanev073** [pop-os/icon-theme#37]
Hi guys,

After I updated my Pop from 18.10 to 19.04 the icons were set to the default ubuntu icons. I tried to install the pop icons but it turned out I have them installed. Is there any way to enable them back? Also it seems some colors changed and I am missing the "organize desktop by name" feature.

Hope someone can suggest a solution. Thanks in advance!

**Comment by cbb330** [comment]
Having this issue as well. It would be great to have tags on this repository so that we could roll back easily.

**Comment by mmstick** [comment]
See https://pop-planet.info/forums/projects/pop-classic.3/
