### ISSUE TITLE
Icons for switching between screenshots are missing in Pop!_Shop

### ISSUE THREAD

**Issue by brs17** [pop-os/icon-theme#38]
**Reporter info**

 * Distribution - (run ```lsb_release -a```)  - Pop!_OS 19.04
 * Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```) - 3.24.8-1ubuntu1
 * Desktop environment - GNOME

**Pop version (if you knew)**
Pop!_OS 19.04

**Related Application and/or Shell theming (or name of widget)**
Pop!_Shop

**Actual issue**
The icons for switching between screenshots is missing.
![shop_icon](https://user-images.githubusercontent.com/7460774/57028829-56487d80-6bfd-11e9-9077-9bf8e0e874de.png)

**Comment by isantop** [comment]
Addressed in #42
