### ISSUE TITLE
Move distributor-logo.svg to distributor-logo-popos.svg and symlink

### ISSUE THREAD

**Issue by mmstick** [pop-os/icon-theme#39]
We have a `distributor-logo.svg` file, but we should also include our logo alongside other existing distributor logos, so that applications can display our logo when requested (idea for the installer).

![screenshot from 2018-11-14 11-39-56](https://user-images.githubusercontent.com/4143535/48504468-171aa180-e802-11e8-94b9-0151ee5b6c8f.png)

**Comment by evertiro** [comment]
I'd suggest also adding an OSX logo, and a generic Linux logo (aka, tux) for anything that is a verified Linux distro without its own logo.

**Comment by mmstick** [comment]
We do have a `tux.svg` icon that works for that purpose. Seems odd that Papirus doesn't already include a  `-macos` and `-linux` icon by default, though.
