### ISSUE TITLE
Certain programs open with different icon than when selected

### ISSUE THREAD

**Issue by brs17** [pop-os/icon-theme#4]
**Reporter info**

 * Pop!_OS 19.04
 * Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```) 3.24.7-1ubuntu1
 * Desktop environment - GNOME

**Pop version (if you knew)**
Pop!_OS 19.04 iso19 

**Actual issue**
When opening any of the following applications, the icon that appears on the favorites bar is different than the icon in the Activities (applications) list. My thought is that there is a missing size/resolution of these icons because once 9 or so applications are present on the favorites bar, the icons are corrected (and smaller).

List of affected icons:
- calc
- calendar
- contacts
- gnome-control-center
- gedit
- disk usage
- disks
- input method
- power stats
- startup application
- system monitor
- archive manager
- evince
- eddy
- fonts
- help
- eog
- videos

Screenshot example of opening the calculator app:
![Screenshot from 2019-04-09 18-58-34](https://user-images.githubusercontent.com/7460774/55883036-cc0f7b00-5b62-11e9-8dac-5c005293c1d5.png)

**Comment by isantop** [comment]
This has been fixed as of 279cbc872bd52da21b04a8a8ab3f84642517af49
