### ISSUE TITLE
Unable to locate package pop-icon-theme

### ISSUE THREAD

**Issue by ocafebabe** [pop-os/icon-theme#41]
**Reporter info**

 * Distribution - Linux Mint 18.3 Sylvia
 * Gtk+ 3.0 version - 3.18.9-1ubuntu3.3
 * Desktop environment - Cinnamon

**Actual issue**

```bash
E: Unable to locate package pop-icon-theme
```

**Steps to reproduce (if you knew)**

```bash
sudo add-apt-repository ppa:system76/pop
sudo apt-get update
sudo apt install pop-icon-theme
```

**Comment by karanrajpal14** [comment]
Same issue here. Don't the packages listed in the PPA either. They must've moved them I reckon.

**Comment by jackpot51** [comment]
We no longer have packages for 16.04 in the PPA. Please update to a newer release of your distribution.
