### ISSUE TITLE
Volume over-amplification icon broken

### ISSUE THREAD

**Issue by v-marinkov** [pop-os/icon-theme#43]
**Reporter info**

 * Distribution - (run ```lsb_release -a```)
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Pop!_OS 19.04
Release:	19.04
Codename:	disco

 * Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```)
libgtk-3-0:
  Installed: 3.24.8-1ubuntu1
  Candidate: 3.24.8-1ubuntu1
  Version table:
 *** 3.24.8-1ubuntu1 500
        500 http://it-mirrors.evowise.com/ubuntu disco/main amd64 Packages
        100 /var/lib/dpkg/status

**Actual issue**
The over-amplification icon for volume beyond 100% looks broken:
![gnome-shell-screenshot-7B562Z](https://user-images.githubusercontent.com/7135724/58711126-1d4b2680-83be-11e9-8df1-9c116402eb86.png)

**Expected behaviour**
All other icon themes including Pop-classic and Adwaita look fine:
![gnome-shell-screenshot-DIYY2Z](https://user-images.githubusercontent.com/7135724/58711221-5b484a80-83be-11e9-8412-232048213151.png)

**Comment by isantop** [comment]
This is the expected Icon in the new theme. The old one doesn't really communicate what's going on, and the new one is intended to indicate that something may be broken with the volume set at this level.

**Comment by v-marinkov** [comment]
I am sorry, but this icon seems very odd. It has straight lines for the over-amplification portion while the normal range is shown with curves. It looks like there's another ghostly icon peeking underneath it. I don't think it suggests that anything else is broken but the icon itself.

**Comment by WatchMkr** [comment]
@isantop let's not change the icon when the volume is amplified. The line changing to red is sufficient and cleaner.

**Comment by v-marinkov** [comment]
@WatchMkr that's better than the current icon, but I still think an additional visual cue would help. For instance, the jump in the wave portion of the icon on Adwaita immediately alerts you that you are going in over-amplification while the red indicator is easy to miss. 

The classic Pop jumps both at the speaker and wave portions and it is not pleasant. The current Pop looks broken. In this case I believe Adwaita does it best so far.

**Comment by PanderMusubi** [comment]
In 20.10 the icon is good when adjusting the normal volume 0 - 100%, but with over amplification 100 - 150% another icon is shown under it which looks like the first image in this issue. Could not capture the current one with GIMP, but looks similar.

**Comment by FlyinPancake** [comment]
I'm really sorry to say this but this icon is half baked and looks truly unprofessional.
The over-amplification is NOT a bug, it's a feature so it does not have to look like a bug in my opinion. Thanks for coming to my TED talk

**Comment by PanderMusubi** [comment]
This is still an issue for

    No LSB modules are available.
    Distributor ID:	Pop
    Description:	Pop!_OS 21.04
    Release:	21.04
    Codename:	hirsute

with

    libgtk-3-0:
      Installed: 3.24.25-1ubuntu4.1
      Candidate: 3.24.25-1ubuntu4.1
      Version table:
     *** 3.24.25-1ubuntu4.1 500
            500 http://nl.archive.ubuntu.com/ubuntu hirsute-updates/main amd64 Packages
            100 /var/lib/dpkg/status
         3.24.25-1ubuntu4 500
            500 http://nl.archive.ubuntu.com/ubuntu hirsute/main amd64 Packages

![overamplification](https://user-images.githubusercontent.com/198964/129018646-d2074b57-fac1-442b-ace3-15776b16b4c5.png)
