### ISSUE TITLE
Installation on other distros fedora, arch, centos

### ISSUE THREAD

**Issue by kashkama** [pop-os/icon-theme#45]
**Reporter info**

 * Distribution - (run ```lsb_release -a```)
 * Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```)
 * Desktop environment - 

**Is this issue an Icon Request?**

_Please note that Icon Requests are considered low-priority. We recommend submitting Icon Requests directly to [upstream Papirus](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues)_

**Pop version (if you knew)**

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Behaviour in Adwaita**

**Other Note (feature-request, question, etc...)**

**Comment by mmstick** [comment]
If you're asking how, instructions are in the README on the front page: https://github.com/pop-os/icon-theme#downloading-pop

**Comment by kashkama** [comment]
Thanks, For the instructions. Good day
