### ISSUE TITLE
panel/caffeine-cup* are vertically misaligned

### ISSUE THREAD

**Issue by arcruz0** [pop-os/icon-theme#48]
**Reporter info**

 * Distribution - Pop!_OS 18.10
 * Gtk+ 3.0 version - 3.24.4-0ubuntu1
 * Desktop environment - Gnome

**Related Application and/or Shell theming (or name of widget)**

Caffeine Gnome Shell Extension

**Actual issue**

The icons (with caffeine on or off) are vertically misaligned in the panel:

![Screenshot from 2019-03-28 15-51-49](https://user-images.githubusercontent.com/28851411/55185384-00526700-5173-11e9-8652-3e67a50a5171.png)

**Expected behaviour**

The caffeine icons are properly aligned in the panel.

**Behaviour in Adwaita**

No caffeine icon.

**Other Note (feature-request, question, etc...)**

Thank you very much!

**Comment by brs17** [comment]
This sounds like an issue with the Caffeine extension, not Pop!_OS. Additionally it looks like the Caffeine extension is no longer being maintained: https://github.com/eonpatapon/gnome-shell-extension-caffeine . Maybe there is a similar extension that is currently being maintained that does not have this issue.
