### ISSUE TITLE
Monochromatic icons present amongst multi-colored icons

### ISSUE THREAD

**Issue by brs17** [pop-os/icon-theme#5]
**Reporter info**

 * Distribution - (run ```lsb_release -a```)
 * Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```) 3.24.7-1ubuntu1
 * Desktop environment - GNOME

**Pop version (if you knew)**
Pop!_OS 19.04 iso19 

**Potential issue**
NetworkManager, Language Support, and GNOME Screenshot all have (monochromatic) white icons when all of the other apps are multicolored. These three apps seem out of place/seem to be using an incorrect icon set.

![Screenshot from 2019-04-09 18-35-07](https://user-images.githubusercontent.com/7460774/55882068-1d1e6f80-5b61-11e9-92be-e66e4f9a108a.png)
![Screenshot from 2019-04-09 18-35-13](https://user-images.githubusercontent.com/7460774/55882071-1d1e6f80-5b61-11e9-9e7b-d6db411c9ba9.png)

**Comment by isantop** [comment]
This was fixed by 279cbc872bd52da21b04a8a8ab3f84642517af49
