### ISSUE TITLE
Pop!_OS logo is not present

### ISSUE THREAD

**Issue by brs17** [pop-os/icon-theme#50]
**Reporter info**

 * Distribution - (run ```lsb_release -a```)
 * Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```) 3.24.7-1ubuntu1
 * Desktop environment - GNOME

**Pop version (if you knew)**
Pop!_OS 19.04 iso 19

**Related Application and/or Shell theming (or name of widget)**
gnome-initial-setup and gnome-control-center (that I know of)

**Actual issue**

The Ubuntu logo is displayed where the Pop!_OS logo should be displayed.

![Pop_icon](https://user-images.githubusercontent.com/7460774/55815556-ca37b000-5aad-11e9-9cad-747eea73ada9.png)
![Screenshot from 2019-04-09 09-36-56](https://user-images.githubusercontent.com/7460774/55815557-cad04680-5aad-11e9-8985-ac31d17657d5.png)

**Comment by isantop** [comment]
The icon being requested is called "ubuntu-logo-icon" 
![Screenshot from 2019-04-09 10-58-56](https://user-images.githubusercontent.com/5883565/55819674-8dbc8200-5ab6-11e9-9275-bbd932d37e0e.png)

The Pop_OS logo is present as distributor logo
