### ISSUE TITLE
19.10: Applications without desktop file has blank space as desktop file replacement

### ISSUE THREAD

**Issue by brs17** [pop-os/icon-theme#50]
**Reporter info**

 * Distribution - (run ```lsb_release -a```) Pop!_OS 19.10
 * Desktop environment - GNOME

**Actual issue**
In 19.04, when repoman is opened, the favorites dash shows an icon that there is a missing icon. On 19.10, there is no icon on the dash.

19.04:
![1904](https://user-images.githubusercontent.com/7460774/66790067-833ad500-eeab-11e9-8ac1-38cbfbf7ab55.png)

19:10:
![1910](https://user-images.githubusercontent.com/7460774/66790074-87ff8900-eeab-11e9-82c0-c9f24d464617.png)

I think the lack of an icon is potentially more confusing than an icon that just symbolizes that there is no specific icon.

**Comment by isantop** [comment]
I don't think this is a change with the icon theme, as this also happens with GNOME Icons and there were no changes to the icon theme between 19.04 and 19.10 (apart from #49 ).
