### ISSUE TITLE
Missing icon for selected subwoofer in GNOME Settings

### ISSUE THREAD

**Issue by brs17** [pop-os/icon-theme#56]
**Reporter info**

 * Distribution - (run ```lsb_release -a```) - Pop!_OS 19.10
 * Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```) 3.24.12-1ubuntu1
 * Desktop environment - GNOME

**Is this issue an Icon Request?**
This is only an icon request in as much as a missing icon is a request.

**Pop version (if you knew)**
19.10

**Actual issue**
When selecting to test the subwoofer in the Sound tab of the GNOME Settings, the subwoofer icon is present until the sound is actually played and then it switches over to an "icon not found" icon. 

It should be noted that when using the Adwaita theme, there does not seem to be a subwoofer icon at all.

**Steps to reproduce (if you knew)**
See attached video (inside zip)

**Behavior in Adwaita**
The entire subwoofer icon seems to be missing entirely.

**Other Note**
Screen recording:
[sub.zip](https://github.com/pop-os/icon-theme/files/4016516/sub.zip)

**Comment by isantop** [comment]
Would it be possible to get the icon-name that's being requested here? It can be found by using the GTK inspector to inspect the icon, then looking under Properties at the `icon-name` prop.
