### ISSUE TITLE
Shotwell and Image Viewer app icons are too similar

### ISSUE THREAD

**Issue by Electw** [pop-os/icon-theme#58]
**Reporter info**

 * Distribution - (Pop!_OS 19.10)
 * Gtk+ 3.0 version - (3.24.12)
 * Desktop environment - GNOME 3.34.1

**Is this issue an Icon Request?**

Yes

**Pop version (if you knew)**

19.10

**Related Application and/or Shell theming (or name of widget)**

Shotwell, Image Viewer

**Actual issue**

The icons for Shotwell and Image Viewer are way too similar. The only difference between them is the tiny red square at the bottom right of the icon, otherwise they are virtually indiscernible with a quick glance.

**Other Note (feature-request, question, etc...)**

Shotwell icon name: ```shotwell.png```
![shotwell](https://user-images.githubusercontent.com/55963122/72210019-334bba00-346a-11ea-80ff-ee5d8dc04c2a.png)
Image Viewer icon name: ```lximage.png``` and ```lximage-qt.png```
![lximage](https://user-images.githubusercontent.com/55963122/72210020-35ae1400-346a-11ea-8d05-a126b9630966.png)

**Comment by isantop** [comment]
Shotwell is a 3rd party application and we should not be shipping any icon for it at all. Thanks for bringing this to our attention!
