### ISSUE TITLE
Broken/missing icons for "select screenshot" and "report a problem"

### ISSUE THREAD

**Issue by lfom** [pop-os/icon-theme#63]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="19.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.10"
VERSION_ID="19.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan
LOGO=distributor-logo-pop-os
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
N: Unable to locate package io.elementary.appcenter
N: Couldn't find any package by glob 'io.elementary.appcenter'
N: Couldn't find any package by regex 'io.elementary.appcenter'

**Issue/Bug Description:**
Broken/missing icons for "select screenshot" and "report a problem"
![Screenshot from 2020-02-29 18-48-12](https://user-images.githubusercontent.com/15659999/75615601-95e53c00-5b24-11ea-97b6-1875ee43e5d4.png)

**Steps to reproduce (if you know):**
Open any app with multiple screenshots and/or "report a problem" link at the bottom, the proper related icons are missing.

**Expected behavior:**
It should show the proper icon instead of "image-missing.png" icon from the current icon theme.

**Other Notes:**
Running "G_MESSAGES_DEBUG=all io.elementary.appcenter" didn't show any messages regarding missing resources, maybe it's broken upstream?

Screenshot showing the problem attached.

**Comment by isantop** [comment]
This is an issue with the Icon theme, rather than with Pop-Shop
