### ISSUE TITLE
Dropbox icon tray missing

### ISSUE THREAD

**Issue by brianmsm** [pop-os/icon-theme#67]
**Describe the problem:** The icon systray doesn't appear in bar notifications
![imagen](https://user-images.githubusercontent.com/28207224/84545170-5d790080-acc4-11ea-88a2-e92236f15e21.png)

**Steps to reproduce:**
1. I installed dropbox from Pop!_Shop.
2. Icon in bar doesn't show.

**Distribution:** Pop!_OS 20.04 LTS

**Pop version:** pop-icon-theme 2.1.0

![imagen](https://user-images.githubusercontent.com/28207224/84545427-e3954700-acc4-11ea-8595-1439c997f490.png)

**Comment by pongloongyeat** [comment]
Mine seems to be working just fine. I'm on Pop!_OS 20.04 LTS as well.

![image](https://user-images.githubusercontent.com/31680656/91008053-138b8f80-e610-11ea-82cb-0c63aa0a4358.png)

**Comment by bemoty** [comment]
Can confirm, the icon is not there for me either. I'm on Pop!OS 20.10 with the newest available version of the icon theme installed
![image](https://user-images.githubusercontent.com/16725421/116400972-f9532280-a82a-11eb-925e-f691a7411ff1.png)

**Comment by isantop** [comment]
Just checking if anyone on this issue is still getting the problem? If so, please report with a screenshot and list of any icon themes you have installed.

**Comment by isantop** [comment]
Closing due to a lack of response to follow up.
