### ISSUE TITLE
Gnome-online-accounts is lacking the Microsoft exchange icon

### ISSUE THREAD

**Issue by brs17** [pop-os/icon-theme#7]
**Reporter info**

 * Distribution - (run ```lsb_release -a```)
 * Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```) 3.24.7-1ubuntu1
 * Desktop environment - GNOME

**Pop version (if you knew)**
Pop!_OS 19.04 iso19

**Related Application and/or Shell theming (or name of widget)**
gnome-online-accounts

**Actual issue**
The Microsoft Exchange icon is missing.

![microsoft_exchange](https://user-images.githubusercontent.com/7460774/55816259-18997e80-5aaf-11e9-8dc9-c4e7f1fe555b.png)

**Comment by isantop** [comment]
Curious that Adwaita seems not to include this icon as well.
