### ISSUE TITLE
Other icon themes seem to have higher priority (Affects cursors too)

### ISSUE THREAD

**Issue by TechnologyMan101** [pop-os/icon-theme#71]
**Describe the problem:**
Other icon themes seem to have higher priority than the Pop Icon Theme. This results in other icons being used instead of the ones from Pop Icon Theme even when Pop is selected in GNOME Tweaks. This happens when there is any other icon theme installed. The only one I have tested as of now is `breeze-icon-theme`. This also happens with cursors (no screenshots provided) where the resize cursors get messed up when there is any other cursor theme installed. This includes, but is not limited to `breeze-cursor-theme` and `dmz-cursor-theme`.

With Pop Icon Theme:
![Screenshot from 2020-10-12 21-23-46](https://user-images.githubusercontent.com/65311278/95815931-b2f50680-0cd2-11eb-8fce-bfff765d7208.png)

With stock Adwaita icons:
![Screenshot from 2020-10-12 21-28-20](https://user-images.githubusercontent.com/65311278/95815949-bc7e6e80-0cd2-11eb-9f26-5f5b0f362d5c.png)

On Ubuntu 20.04 LTS:
![Screenshot from 2020-10-13 14-23-29](https://user-images.githubusercontent.com/65311278/95918046-fcd7fe00-0d5f-11eb-9ff9-8773c6809af4.png)

**Steps to reproduce:**
1. Install KDenlive (`sudo apt install -y kdenlive`)
2. Icons have changed. The most obvious is LibreOffice. This also includes KDenlive itself, KDE Connect, and VLC. This is due to the Breeze icon theme being installed as a dependency.

**Distribution:**
Pop!_OS 20.04 LTS

**Pop version:**
2.1.0~1602083697~20.04~5a9a850

**Comment by isantop** [comment]
I believe this is an issue with theme inheritance. Pop does not ship application icons, but does inherit Breeze, which apparently does. Let's track this through the inheritance issue #94
