### ISSUE TITLE
Mission icon: display-symbolic

### ISSUE THREAD

**Issue by bryanpaget** [pop-os/icon-theme#73]
**Description of the problem:**

![image](https://user-images.githubusercontent.com/8212170/97065179-6bf0f600-159b-11eb-981e-d614b2188b00.png)

A non symbolic icon is being used on the "Screen" button in the screenshot app.

**Steps to reproduce:**

1. Open the app.

**Pop version:**

Running Pop 20.10.

GTK Theme version installed: 5.3.0\~1603307552~20.10\~a5e0cc9

**Comment by bryanpaget** [comment]
I've investigated the issue with GNOME and I think the issue may result from the included `gnome-icon-theme` which is overriding the `display` icon.

See [here](https://gitlab.gnome.org/GNOME/gnome-screenshot/-/issues/125) for more information.

**Comment by TechnologyMan101** [comment]
Yes, that is the problem as the file for the icon in the Pop Theme is there. Note that this bug also happens when using Ubuntu with vanilla GNOME too so it is not specific to Pop!_OS.

**Comment by TechnologyMan101** [comment]
Basically, it's a problem that seems to come from upstream.

**Comment by isantop** [comment]
In the meantime, we've added a `display-symbolic` icon which should fix this issue.
