### ISSUE TITLE
local install causes cursor issue on wayland

### ISSUE THREAD

**Issue by khensunny** [pop-os/icon-theme#76]
**Describe the problem:**

A local install (prefix $HOME/.local) has an issue on wayland, the cursor is only correct on the shell but on applications it turns to some ugly looking cursor which I guess is some system fallback. Furthermore, soon as you change the cursor from whatever it was to the locally installed Pop cursor, the shell might crash or some other random app (was gnome-terminal first, then Firefox).

![image](https://user-images.githubusercontent.com/44401412/102031721-7cfdfc80-3dbf-11eb-9bab-3571394ab4bc.png)

**Steps to reproduce:**
1. switch to wayland
2. do local install of icon-theme (meson -Dprefix=$HOME/.local build ; ninja -C "build" install)

**Distribution:**

"Fedora 33 (Workstation Edition)"

**Pop version:**

    
commit: 5a9a850ae6b3b7059a940baaff40aa7d5d81eb50

**Comment by isantop** [comment]
Thanks for your report! I believe the issue is that Wayland applications don't necessarily have access to your local theme folder, so installing the icon theme system-wide will be required.
