### ISSUE TITLE
Missing Pop!_OS battery icon

### ISSUE THREAD

**Issue by tst05000** [pop-os/icon-theme#79]
I don't know if this has to do with Arch Linux or with my gnome version but after installing and setting my icon theme as "Pop" every icon at the shell changed to the pop os variant but the battery stayed the stock icon rather than changing into the pop os variant, although i don't know if i'm doing somthing wrong, I did try the AUR but it was the same one and so i tried the git clone and manual installation via terminal but to no avail.

**Comment by tst05000** [comment]
Okay so I realised that theres an extension on guthub called pop battery icon fix which is made by the pop-os team and after installing it rebooting and enabling the extension it basically fixed it so... yeah

**Comment by jacobgkau** [comment]
The extension should not be necessary anymore once https://github.com/pop-os/icon-theme/pull/78 is merged.
