### ISSUE TITLE
Icons missing in installer

### ISSUE THREAD

**Issue by brs17** [pop-os/icon-theme#8]
**Reporter info**

 * Distribution - (run ```lsb_release -a```)
 * Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```) 3.24.7-1ubuntu1
 * Desktop environment - GNOME

**Pop version (if you knew)**
Pop!_OS 19.04 debug iso 19

**Related Application and/or Shell theming (or name of widget)**
pop-installer

**Actual issue**
There are a few missing icons in the installer as seen in the screenshots below.
![Screenshot from 2019-04-09 15-21-06](https://user-images.githubusercontent.com/7460774/55813922-db32f200-5aaa-11e9-9547-50e3baa2f51e.png)
![Screenshot from 2019-04-09 15-21-23](https://user-images.githubusercontent.com/7460774/55813923-db32f200-5aaa-11e9-8bee-1e9350700bc1.png)

**Comment by isantop** [comment]
Addressed in 63f39d284e97ce52650145a422357cc8bb19e98a

We will need to have a better fix for the long run, as this includes a themed icon for gcleaner as-is. However, in the interest of releasing on time, that is acceptable.

![Screenshot from 2019-04-15 15-17-47](https://user-images.githubusercontent.com/5883565/56166171-1e510180-5f92-11e9-9067-eab76e7c75db.png)
