### ISSUE TITLE
Meld Icons doesn't look good with pop Icon theme

### ISSUE THREAD

**Issue by stutzzzz** [pop-os/icon-theme#87]
**Describe the problem:**
Meld Icons doesn't look right with PoP Icon Theme I think these icons are for light not dark themes

**Steps to reproduce:**
1. Open Meld

**Distribution:** PRETTY_NAME="Pop!_OS 21.04"

**Pop version:** Installed: 2.1.0~1626456130~21.04~8e5d8ca

    
![image](https://user-images.githubusercontent.com/28896682/129124275-37d7fb68-385e-4840-9b60-4eaa782e430d.png)
using default gnome icons
![image](https://user-images.githubusercontent.com/28896682/129124334-2833d39b-c8eb-4b4e-afa4-95a45eafdd0b.png)

**Comment by stutzzzz** [comment]
I think I found the arrow icons looking for the Doc Icon Using Icon Browser it appears to be go-previous,next,down,up
![image](https://user-images.githubusercontent.com/28896682/135483425-512a4c4e-c0aa-4dbd-9b85-dcf8ee0ffb01.png)

**Comment by isantop** [comment]
Thanks for the report! I looks like Meld is not requesting symbolic icons, which prevents Gtk from re-coloring the Icons dynamically to match the theme. Unfortunately, this issue cannot be fixed in the icon theme, because modifying the icons to have good contrast in the dark theme makes them invisible in the light theme (and vice-versa).

**Comment by stutzzzz** [comment]
it appears that flatpak version doesn't have as big of an issue compared to the deb.
![image](https://user-images.githubusercontent.com/28896682/136594469-626ad442-2d71-4072-8fa0-cc7488d34c89.png)
looks like its only the arrow icons for previous and next change
![image](https://user-images.githubusercontent.com/28896682/136594824-a2d1c93f-876e-49a2-b0a4-b6cb569a9a87.png)

**Comment by jacobgkau** [comment]
> modifying the icons to have good contrast in the dark theme makes them invisible in the light theme (and vice-versa).

Given that the dark theme is currently the default, would it make sense to prioritize that one?

Looking at Adwaita's icon theme, they're using colors that are visible in both the light and dark theme (but have more contrast in the dark theme, even though they default to light.)

**Comment by isantop** [comment]
Should be improved as of #99 , please feel free to reopen if contrast issues persist
